### ISSUE TITLE
The restore_state option has been removed in 2023.7.0

### ISSUE THREAD

**Issue by Drewskieza** [EverythingSmartHome/everything-presence-one#84] opened 2023-07-19 11:10 UTC
It looks like the new version of ESPHome is causign an issue.
This is hte error I get when I try update my EP1 to the latest version.
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/34630805/cc68c65c-2677-4281-a3f9-7c667938cd0b)

**Comment by EverythingSmartHome** [comment] 2023-07-19 11:23
This is a duplicate of https://github.com/EverythingSmartHome/everything-presence-one/issues/83

Should be resolved already, you may need to clear cache.

**Closed by EverythingSmartHome** 2023-07-19 11:23 UTC
